"use client";
import Navbar from "@/components/NavBar/Navbar";
import "./globals.css";
import { fonts } from "@/utlis/fonts/font";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <body className={fonts.nunito.className}>
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </body>
      </QueryClientProvider>
    </html>
  );
}
