import Navbar from "@/components/NavBar/Navbar";
import "./globals.css";
import { fonts } from "@/utlis/fonts/font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fonts.plus_Jakarta_Sans.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
