import Navbar from "@/components/NavBar/Navbar";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";

const plus_Jakarta_Sans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plus_Jakarta_Sans.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
